### ISSUE TITLE
feedback command

### ISSUE THREAD

**Issue by avirsaha** [avirsaha/theclassmatebot#1]
Create functionality for the /feedback command of theclassmatebot. Take feedback from the user and sent it to a particular email. If not possible then save it in some file.

### Issue Description
**Overview:**
Implement the already declared methods for /feedback command and allow the users to give feedback. Sent the valuable feedbacks to a particular email or save them in a file without username or identity of any sort.

**Tasks:**
1. **Implement the /feedback related functions:**
    - Implement the already declared functions.
    - Declare and implement new functionalities to store or sent the data.
2. **Optimize:**
    - Keep performance in mind as server resources are limited
    - Display appropriate debug messages.
3. **Privacy & Security:**
    - Add relevant documentation to README.md
    - Do not share sensitive information such as email IDs.
    - Add PRIVACY-POLICIES.md stating clearly about the type of data collected.
   
**Acceptance Criteria:**
- The code should adhere the standard PEP-8 guidelines.
- All new functionalities should be tested first.
- Exceptions should be handled properly for edge cases.
- Code changes should be well-documented and follow the project's coding standards.

**Comment by Roguemaths** [comment]
Working on it.
